### ISSUE TITLE
new empty ‘outputs’ field problem

### ISSUE THREAD

**Issue by Zambonifofex** [bcomnes/deploy-to-neocities#10]
Hello! :wave:

Until yesterday, I was effectively using this project to deploy my website to Neocities. (Thank you for that!)

Today, it seems something changed (I imagine on GitHub’s side), and this stopped working for me.

Now, I get an error that looks like this:

~~~
##[error]bcomnes/deploy-to-neocities/v1/action.yml (Line: 18, Col: 9): Unexpected value ''
##[error]System.ArgumentException: Unexpected type 'NullToken' encountered while reading 'outputs'. The type 'MappingToken' was expected.
~~~

I do not understand YAML nor GitHub actions well enough, but I assume what happened is that GitHub stopped accepting an empty value for `outputs`. I’d imagine a simple enough fix would be to comment out (or remove altogether) the `outputs` field from [`action.yml`](https://github.com/bcomnes/deploy-to-neocities/blob/7dce130590457fee0823c708884cb309fedc140c/action.yml#L18).

Thank you once again for having worked on this project! :tada:

**Comment by bcomnes** [comment]
Cool breaking change GitHub actions!  What used to work no longer does apparently. 

Yeah looks like someone made a PR to address the trivial change.  I’ll land as soon as I get to the keys.

**Comment by bcomnes** [comment]
Should be fixed, auto updated for you if you are running v1.

**Comment by bcomnes** [comment]
Thanks everyone.

**Comment by bcomnes** [comment]
What a cool simple site btw:

https://github.com/Zambonifofex/stories

Mind if I add the repo to the `Sites using deploy-to-neocitie` section of the README here?

**Comment by Zambonifofex** [comment]
@bcomnes: Apologies for not having responded sooner, I just saw your message. :thinking:

Thank you so much for the compliment! :blush: Of course you can feel free to add it to your README. :tada:

Interestingly enough, before reading your message here, I have recently added Web feed support to the website, and I used some of your libraries to achieve that more easily. So thank you for that too! (I’m looking forward for support for JSON feed 1.1, which was coincidentally released just yesterday.)

**Comment by bcomnes** [comment]
Glad someone is finding them useful!

Yeah I need to visit 1.1 soon ok the json-feed-to-* modules. Looks pretty easy, author is changed to authors and a couple of other small changes.

**Comment by bcomnes** [comment]
Added!
