### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by pdmcharms** [bcomnes/deploy-to-neocities#116]
Hi, thank you for helping me with the last issue I had. I've updated the workflows file and added in the dependabot.yml file like you said. When the commit is pushed this time, i'm getting an error that reads as above. Any idea what this could be? Thanks!

**Comment by bcomnes** [comment]
https://github.com/pdmcharms/11ty-Neo/blob/17b79f0ffdb58627f12ba0b79e5103880c7230e6/.github/workflows/main.yml#L28

This step is failing. You can either modify your workflow file, or add a build script to the package.json.

**Comment by bcomnes** [comment]
Closing until there is something actionable here.
