### ISSUE TITLE
Problems with using the base repo/root directory as the content to be deployed

### ISSUE THREAD

**Issue by cmdonovann** [bcomnes/deploy-to-neocities#127]
Got a BadRequest error when trying to use the base repo/root directory as the content to be deployed. I tried modifying the last line of the .yml file from "dist_dir: public" to "dist_dir: /" and "dist_dir: ." with no luck. 

I solved this by moving everything in my base repo/root directory (except the .github folder) into a folder labeled "public" and deploying that instead. 

If this is expected, is it possible to put a warning to let people know they can't do this?

**Comment by bcomnes** [comment]
Yeah need to improve this but just haven't had time. Trying to deploy the root folder would generally include .git, .github and other files that neocities rejects. It's better to have a subfolder that has the actual site contents that is statically deployed or built out on every deploy.

**Comment by bcomnes** [comment]
A docs update would be an easy way to clarify this, but also ignore rules or a printing a warning or something would also help out.

**Comment by bcomnes** [comment]
Ok updated the readme.

**Comment by bcomnes** [comment]
Closing for now.
