### ISSUE TITLE
Improve ignore settings

### ISSUE THREAD

**Issue by bcomnes** [bcomnes/deploy-to-neocities#133]
People keep wanting to deploy folders with .git in them. We should just ignore these by default instead of letting the neocities API reject it.

**Comment by character42** [comment]
Why not just ignore anything that is not of a valid file type?? 
(html htm txt text css js jpg jpeg png apng gif svg md markdown eot ttf woff woff2 json geojson csv tsv mf ico pdf asc key pgp xml mid midi manifest otf webapp less sass rss kml dae obj mtl scss webp avif xcf epub gltf bin webmanifest knowl atom opml rdf map gpg resolveHandle pls yaml yml toml osdx)

Or add some sort of ignore function in the configuration where users are able to specify the files they want the action to ignore.

**Comment by bcomnes** [comment]
Yup! Thats the idea

**Comment by bcomnes** [comment]
I implemented unsupported file type filtering. An ignore feature is also probably warranted, but lets just go with that for now.
