### ISSUE TITLE
Problems with deploying neofeed-theme

### ISSUE THREAD

**Issue by Celine1986** [bcomnes/deploy-to-neocities#166]
I’ve tried to follow all of the steps with deploying my neocities site out of github directly with neofeed-theme, but I keep getting “Error: must pass apiKey as first argument”

**Comment by bcomnes** [comment]
Did you grab your API key from neocities, set it as an action secret, and pass it to the action as configured here?

https://github.com/bcomnes/deploy-to-neocities/blob/2fe29239c9779bf8676ea0a330de76ca70b65126/.github/workflows/neocities.yml#L35

The symptoms make it sound like `secrets.NEOCITIES_API_TOKEN` might be undefined.

**Comment by Celine1986** [comment]
Yes, I've did defined the secret key :/
idk what I'm doing wrong...

**Comment by bcomnes** [comment]
Can you share your code?

**Comment by Celine1986** [comment]
https://github.com/Celine1986/neofeed-theme

**Comment by bcomnes** [comment]
Did you figure it out?

**Comment by Celine1986** [comment]
I’m using the Hugo method instead :)
