### ISSUE TITLE
npm ERR! enoent 

### ISSUE THREAD

**Issue by goldstargloww** [bcomnes/deploy-to-neocities#168]
hilo o/ when this runs, it gets to the "Install deps and build" step, and then throws an error

```
Run npm i
  npm i
  npm run build
  shell: /usr/bin/bash -e {0}
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/runner/work/starglowwos-neocities/starglowwos-neocities/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/runner/work/starglowwos-neocities/starglowwos-neocities/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/2024-01-07T02_37_52_038Z-debug-0.log
Error: Process completed with exit code 254.
```
i'd go check `/home/runner/.npm/_logs/2024-01-07T02_37_52_038Z-debug-0.log` but i have absolutely no idea where that is lol

**Comment by bcomnes** [comment]
Do you have the code or action run you can link to?

**Comment by goldstargloww** [comment]
[here](https://github.com/goldstargloww/starglowwos-neocities/actions/runs/7436295451/job/20232593914#step:4:15)'s the action run, and no i don't think it has a package.json

**Comment by bcomnes** [comment]
Ah yeah I see, if you are just deploying static files (no site build) you can delete the npm install step and the setup node step. The Checkout step is still required though. Does that help?

**Comment by goldstargloww** [comment]
it does yeah ^^ i'm just not sure how to do that is the thing lol

**Comment by bcomnes** [comment]
Just delete these lines: https://github.com/goldstargloww/starglowwos-neocities/blob/0311c19b5cab07e72f2d6964d2097811d9d2edf3/.github/workflows/neocities.yml#L21-L28

**Comment by goldstargloww** [comment]
that works, thanks :D
