### ISSUE TITLE
Update to Node.js 20

### ISSUE THREAD

**Issue by toritried** [bcomnes/deploy-to-neocities#174]
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: bcomnes/deploy-to-neocities@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

[https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

**Comment by bcomnes** [comment]
Thanks, will do an update asap. Things will keep working for a bit.
