### ISSUE TITLE
Workflow file does not work even after updating actions/checkout@v3 and actions/setup-node@v3 to v4

### ISSUE THREAD

**Issue by irregularhound** [bcomnes/deploy-to-neocities#181]
Out of nowhere, my Neocities workflow file, which up to this point was the one [here](https://scumsuck.com/resources/deployneocities/), stopped working. It has to do with something regarding Node upgrading from version 16 to version 20. I've gone to this GitHub action to replace the workflow file with [this one](https://github.com/bcomnes/deploy-to-neocities?tab=readme-ov-file#usage). After looking around and trying to figure out why it wasn't working, I was able to at least update the actions/checkout@v3 and actions/setup-node@v3 to the 4th version, and use the 2.0.2 version of the GitHub action.
The problem is I still can't deploy my website, and it's because of this error:
![Screenshot 2024-04-30 192315](https://github.com/bcomnes/deploy-to-neocities/assets/101528411/859e4ed8-b3c0-4901-a1de-77b0dfefd365)
I have no idea on what I'm doing here, and some advice on how to fix this would be appreciated.

**Comment by bcomnes** [comment]
The npm install step failed. Did you skip the checkout step? Does your project even need to install npm dependencies? It seems like you modified for your action file without considering what individual steps it was taking.

Send me a URL to the failed action run and I can advise further. Screenshots provide almost no context.
