### ISSUE TITLE
Simplify action example

### ISSUE THREAD

**Issue by bcomnes** [bcomnes/deploy-to-neocities#182]
I thought it would be helpful to people to see an example of a build step in a website but it really just confuses many people. 

Sites that build with `npm` deps should just use the upstream CLI, and action users should just see an example where a folder in a repo gets deployed, with no other steps to confuse the process.

**Comment by Len42** [comment]
I never used Actions until an hour ago, and I was a bit confused by this. In particular, I wondered if the line "uses: actions/setup-node@v3" would be required to run the deploy action (but apparently not).

Maybe just comment out the build step so it still serves as an example but won't mess things up when someone just copies the yml file verbatim.

**Comment by bcomnes** [comment]
I added a comment about removing the node step.
