### ISSUE TITLE
How do I use this action?

### ISSUE THREAD

**Issue by Woolton** [bcomnes/deploy-to-neocities#61]
### Discussed in https://github.com/bcomnes/deploy-to-neocities/discussions/60

<div type='discussions-op-text'>

<sup>Originally posted by **Woolton** November 21, 2021</sup>
This is my first time using actions and I just can't figure it out, as much as I update my [repo](github.com/woolton/woolneocities), no change is reflected on my neocities site. How do I know if the action is even triggering?</div>

**Comment by bcomnes** [comment]
Hey, going to close this issue in favor of the discussion thread. Feel free to open any new issues for bugs or other implementation specific improvements needed.
