### ISSUE TITLE
The `Zeit` notation is clearly out of date.

### ISSUE THREAD

**Issue by fu-sen** [bcomnes/deploy-to-neocities#92]
https://github.com/bcomnes/deploy-to-neocities#what-are-some-of-the-drawbacks-compared-to-netlifyzeit

I understand it's ZEIT now.sh,
but it's now [▲Vercel](https://vercel.com/)

Vercel has increased various functions. Therefore, the comparison with Neocities is not suitable now.
(Some people think that the current Vercel can't deploy .html files directly. It can, but it's not explained)

You may need to remove or update that description.

Of course this should also be reflected in https://deploy-to-neocities.neocities.org/ .

**Comment by bcomnes** [comment]
Ok, updated! Thanks for pointing this out.

**Comment by fu-sen** [comment]
You may need to improve your comparison, but changing Zeit to Vercel is sufficient.
I may close this issue.

**Comment by bcomnes** [comment]
Just to clarify, the comparison is negatives/positives neocities has in reference to vercel and netlify. Clarifying purpose and capabilities of netlify and vercel is out of scope of the docs here. The docs are open to direct suggestion though if you have ideas.

**Comment by fu-sen** [comment]
You may not know the original purpose of the Neocities:
https://twitter.com/kyledrake/status/337706291801763841

As a result, Neocties have a fundamentally different purpose than Vercel and Netlify.
A closer service is Surge (surge.sh), as well.

I feel like you can remove this item.

**Comment by bcomnes** [comment]
Familiar. I'll add the link!
